=== 1DeliDolu/SQL-und-JavaScript/Praxis/imdb/data/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation xml:lang="de">
            Movies
        </xs:documentation>
    </xs:annotation>
    <!-- Root element -->
    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="index" type="xs:positiveInteger"/>
                            <xs:element name="movie_name" type="nichtLeererString"/>
                            <xs:element name="year_of_release" type="xs:positiveInteger"/>
                            <xs:element name="category" type="RatingType"/>
                            <xs:element name="run_time" type="xs:positiveInteger"/>
                            <xs:element name="genres">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="genre" type="GenreType" maxOccurs="5"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="imdb_rating">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="3"/>
                                        <xs:fractionDigits value="1"/>
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="votes" type="xs:positiveInteger"/>
                            <xs:element name="gross_total">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">   <!-- Wert bleibt als decimal -->
                                            <xs:attribute name="currency" type="xs:string" use="required"/>
                                            <xs:attribute name="scale" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Enumeration f端r Genres -->
    <xs:simpleType name="GenreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Action"/>
            <xs:enumeration value="Adventure"/>
            <xs:enumeration value="Animation"/>
            <xs:enumeration value="Biography"/>
            <xs:enumeration value="Comedy"/>
            <xs:enumeration value="Crime"/>
            <xs:enumeration value="Drama"/>
            <xs:enumeration value="Fantasy"/>
            <xs:enumeration value="Family"/>
            <xs:enumeration value="Film-Noir"/>
            <xs:enumeration value="History"/>
            <xs:enumeration value="Horror"/>
            <xs:enumeration value="Music"/>
            <xs:enumeration value="Musical"/>
            <xs:enumeration value="Mystery"/>
            <xs:enumeration value="Romance"/>
            <xs:enumeration value="Sci-Fi"/>
            <xs:enumeration value="Sport"/>
            <xs:enumeration value="Thriller"/>
            <xs:enumeration value="War"/>
            <xs:enumeration value="Western"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- F端r enumieretion catergory-->
    <!-- Enumeration f端r Altersfreigaben -->
    <xs:simpleType name="RatingType">
        <xs:restriction base="nichtLeererString">
            <xs:enumeration value="R"/>
            <xs:enumeration value="PG"/>
            <xs:enumeration value="PG-13"/>
            <xs:enumeration value="G"/>
            <xs:enumeration value="Passed"/>
            <xs:enumeration value="Approved"/>
            <xs:enumeration value="GP"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nichtLeererString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value=".+"/>
            <!-- Regex f端r nicht leeren String -->
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== 1DeliDolu/SQL-und-JavaScript/Praxis/xml-demos/xml-schema/Movie/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="movies.xsd">
    <movie id="1">
        <index>1</index>
        <movie_name>The Godfather</movie_name>
        <year_of_release>1972</year_of_release>
        <category>R</category>
        <run_time>175</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>9.2</imdb_rating>
        <votes>1860471</votes>
        <gross_total currency="$" million="M">134.97</gross_total>
    </movie>
    <movie id="2">
        <index>2</index>
        <movie_name>The Silence of the Lambs</movie_name>
        <year_of_release>1991</year_of_release>
        <category>R</category>
        <run_time>118</run_time>
        <genres>
            <genre>Crime</genre>
            <genre>Drama</genre>
            <genre>Thriller</genre>
        </genres>
        <imdb_rating>8.6</imdb_rating>
        <votes>1435344</votes>
        <gross_total currency="$" million="M">130.74</gross_total>
    </movie>
    <movie id="3">
        <index>3</index>
        <movie_name>Star Wars: Episode V - The Empire Strikes Back</movie_name>
        <year_of_release>1980</year_of_release>
        <category>PG</category>
        <run_time>124</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Adventure</genre>
            <genre>Fantasy</genre>
        </genres>
        <imdb_rating>8.7</imdb_rating>
        <votes>1294805</votes>
        <gross_total currency="$" million="M">290.48</gross_total>
    </movie>
    <movie id="4">
        <index>4</index>
        <movie_name>The Shawshank Redemption</movie_name>
        <year_of_release>1994</year_of_release>
        <category>R</category>
        <run_time>142</run_time>
        <genres>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>9.3</imdb_rating>
        <votes>2683302</votes>
        <gross_total currency="$" million="M">28.34</gross_total>
    </movie>
    <movie id="5">
        <index>5</index>
        <movie_name>The Shining</movie_name>
        <year_of_release>1980</year_of_release>
        <category>R</category>
        <run_time>146</run_time>
        <genres>
            <genre>Drama</genre>
            <genre>Horror</genre>
        </genres>
        <imdb_rating>8.4</imdb_rating>
        <votes>1025560</votes>
        <gross_total currency="$" million="M">44.02</gross_total>
    </movie>
    <movie id="6">
        <index>6</index>
        <movie_name>Casablanca</movie_name>
        <year_of_release>1942</year_of_release>
        <category>PG</category>
        <run_time>102</run_time>
        <genres>
            <genre>Drama</genre>
            <genre>Romance</genre>
            <genre>War</genre>
        </genres>
        <imdb_rating>8.5</imdb_rating>
        <votes>574092</votes>
        <gross_total currency="$" million="M">1.02</gross_total>
    </movie>
    <movie id="7">
        <index>7</index>
        <movie_name>One Flew Over the Cuckoo's Nest</movie_name>
        <year_of_release>1975</year_of_release>
        <category>R</category>
        <run_time>133</run_time>
        <genres>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>8.7</imdb_rating>
        <votes>1010102</votes>
        <gross_total currency="$" million="M">112.00</gross_total>
    </movie>
    <movie id="8">
        <index>8</index>
        <movie_name>Indiana Jones and the Raiders of the Lost Ark</movie_name>
        <year_of_release>1981</year_of_release>
        <category>PG</category>
        <run_time>115</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Adventure</genre>
        </genres>
        <imdb_rating>8.4</imdb_rating>
        <votes>969143</votes>
        <gross_total currency="$" million="M">248.16</gross_total>
    </movie>
    <movie id="9">
        <index>9</index>
        <movie_name>The Lord of the Rings: The Return of the King</movie_name>
        <year_of_release>2003</year_of_release>
        <category>PG-13</category>
        <run_time>201</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Adventure</genre>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>9.0</imdb_rating>
        <votes>1849082</votes>
        <gross_total currency="$" million="M">377.85</gross_total>
    </movie>
    <movie id="10">
        <index>10</index>
        <movie_name>Star Wars: Episode IV - A New Hope</movie_name>
        <year_of_release>1977</year_of_release>
        <category>PG</category>
        <run_time>121</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Adventure</genre>
            <genre>Fantasy</genre>
        </genres>
        <imdb_rating>8.6</imdb_rating>
        <votes>1367430</votes>
        <gross_total currency="$" million="M">322.74</gross_total>
    </movie>
    <movie id="11">
        <index>11</index>
        <movie_name>The Dark Knight</movie_name>
        <year_of_release>2008</year_of_release>
        <category>PG-13</category>
        <run_time>152</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Crime</genre>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>9</imdb_rating>
        <votes>2656768</votes>
        <gross_total currency="$" million="M">534.86</gross_total>
    </movie>

    <movie id="12">
        <index>12</index>
        <movie_name>The Godfather: Part II</movie_name>
        <year_of_release>1974</year_of_release>
        <category>R</category>
        <run_time>202</run_time>
        <genres>
            <genre>Crime</genre>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>9</imdb_rating>
        <votes>1273349</votes>
        <gross_total currency="$" million="M">57.30</gross_total>
    </movie>

    <movie id="13">
        <index>13</index>
        <movie_name>Aliens</movie_name>
        <year_of_release>1986</year_of_release>
        <category>R</category>
        <run_time>137</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Adventure</genre>
            <genre>Sci-Fi</genre>
        </genres>
        <imdb_rating>8.4</imdb_rating>
        <votes>720623</votes>
        <gross_total currency="$" million="M">85.16</gross_total>
    </movie>

    <movie id="14">
        <index>14</index>
        <movie_name>Schindler's List</movie_name>
        <year_of_release>1993</year_of_release>
        <category>R</category>
        <run_time>195</run_time>
        <genres>
            <genre>Biography</genre>
            <genre>Drama</genre>
            <genre>History</genre>
        </genres>
        <imdb_rating>9</imdb_rating>
        <votes>1357621</votes>
        <gross_total currency="$" million="M">96.90</gross_total>
    </movie>

    <movie id="15">
        <index>15</index>
        <movie_name>Inception</movie_name>
        <year_of_release>2010</year_of_release>
        <category>PG-13</category>
        <run_time>148</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Adventure</genre>
            <genre>Sci-Fi</genre>
        </genres>
        <imdb_rating>8.8</imdb_rating>
        <votes>2356293</votes>
        <gross_total currency="$" million="M">292.58</gross_total>
    </movie>

    <movie id="16">
        <index>16</index>
        <movie_name>The Lord of the Rings: The Fellowship of the Ring</movie_name>
        <year_of_release>2001</year_of_release>
        <category>PG-13</category>
        <run_time>178</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Adventure</genre>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>8.8</imdb_rating>
        <votes>1878557</votes>
        <gross_total currency="$" million="M">315.54</gross_total>
    </movie>

    <movie id="17">
        <index>17</index>
        <movie_name>Alien</movie_name>
        <year_of_release>1979</year_of_release>
        <category>R</category>
        <run_time>117</run_time>
        <genres>
            <genre>Horror</genre>
            <genre>Sci-Fi</genre>
        </genres>
        <imdb_rating>8.5</imdb_rating>
        <votes>885635</votes>
        <gross_total currency="$" million="M">78.90</gross_total>
    </movie>

    <movie id="18">
        <index>18</index>
        <movie_name>Saving Private Ryan</movie_name>
        <year_of_release>1998</year_of_release>
        <category>R</category>
        <run_time>169</run_time>
        <genres>
            <genre>Action</genre>
            <genre>Drama</genre>
            <genre>War</genre>
        </genres>
        <imdb_rating>8.6</imdb_rating>
        <votes>1337524</votes>
        <gross_total currency="$" million="M">216.54</gross_total>
    </movie>

    <movie id="19">
        <index>19</index>
        <movie_name>The Departed</movie_name>
        <year_of_release>2006</year_of_release>
        <category>R</category>
        <run_time>151</run_time>
        <genres>
            <genre>Crime</genre>
            <genre>Drama</genre>
            <genre>Thriller</genre>
        </genres>
        <imdb_rating>8.5</imdb_rating>
        <votes>1338281</votes>
        <gross_total currency="$" million="M">132.38</gross_total>
    </movie>

    <movie id="20">
        <index>20</index>
        <movie_name>Pulp Fiction</movie_name>
        <year_of_release>1994</year_of_release>
        <category>R</category>
        <run_time>154</run_time>
        <genres>
            <genre>Crime</genre>
            <genre>Drama</genre>
        </genres>
        <imdb_rating>8.9</imdb_rating>
        <votes>1852527</votes>
        <gross_total currency="$" million="M">107.93</gross_total>
    </movie>
    <movie id="21">
        <index>21</index>
        <movie_name>Apocalypse Now</movie_name>
        <year_of_release>1979</year_of_release>
