=== 1DeliDolu/SQL-und-JavaScript/Praxis/xml-demos/xml-schema/zeitangaben.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation xml:lang="de">
		Demo verschiedener Möglichkeiten der Zeitangabe
		xs:time			täglich wiederkehrende Zeit
		xs:dateTime		Zeitmoment an einem bestimmten Datum
		xs:duration		Zeitdauer
		sind als union-Typ für das Element zeit definiert
		</xs:documentation>
	</xs:annotation>
	<xs:element name="zeitangaben">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="zeit" type="zeitangabentyp" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="zeitangabentyp">
		<xs:union memberTypes="xs:time xs:dateTime xs:duration" />
	</xs:simpleType>
</xs:schema>

=== 1DeliDolu/SQL-und-JavaScript/Praxis/xml-demos/xml-schema/zeitangaben.xml
<?xml version="1.0" encoding="UTF-8"?>
<zeitangaben xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="./zeitangaben.xsd">
	<!-- Zeit muss mit Stunde, Minute und Sekunde angegeben werden -->
	<zeit>16:23:30</zeit>
	<!-- Zeitangabe mit Zeitzone -->
	<zeit>16:23:05+01:00</zeit>
	<!-- Sekundenbruchteile -->
	<zeit>16:23:10.234</zeit>
	<!-- Zeit an Datum, Z steht für GMT Zeitzone -->
	<zeit>2008-08-15T16:23:10.234Z</zeit>
	<!-- Zeit mit Zeitzone -->
	<zeit>2008-08-15T16:23:10.234+01:00</zeit>
	<!-- Zeitdauer, P für Period
		9 Monate und 4 Tage -->
	<zeit>P9M4D</zeit>
	<!-- 1 Jahr 2 Monate 3 Tage 10 Std. 30 Minuten 12,3 Sekunden -->
	<zeit>P1Y2M3DT10H30M5.3S</zeit>
	<zeit>P1Y2M3DT10H30M12.3S</zeit>
	<zeit>P1Y2M3DT2H30M12.3S</zeit>
	<!-- negative Dauer ist zulässig -->
	<zeit>-P3D</zeit>
</zeitangaben>
